import { test, expect } from "@playwright/test"

test.use({
    baseURL: 'https://stg-app.bosta.co',
    extraHTTPHeaders: {
        // We set this header per GitHub guidelines.
        'content-type': 'application/json',
        'Authorization': 'bca27763f5f30353ba0ee3d2ebd8951994f5016e269bbd781798e2884274d631'
    },
});

const createPickupPayload = {
    "businessLocationId": "MFqXsoFhxO",
    "contactPerson": {
        "_id": "_sCFBrHGi",
        "name": "testname",
        "email": "amira.mosa+991^@bosta.co",
        "phone": "+201055592829"
    },
    "scheduledDate": "2025-12-28",
    "numberOfParcels": "3",
    "hasBigItems": false,
    "repeatedData": {
        "repeatedType": "One Time"
    },
    "creationSrc": "Web"
}

const forgetPassPayload = {"email":"amira.mosa+991^@bosta.co"}

test("Create Pickup Endpoint", async ({ request }) => {
    
    //******* Create Pickup EndPoint *********//
    const res = await request.post("/api/v2/pickups", {
        timeout: 3000,
        data: createPickupPayload
    }); 
    
    let resBody = await res.json();
    console.log(resBody); 
    
    expect(res.status()).toBe(200); 
    expect(res.statusText()).toBe("OK"); 


    //******* Forget Password EndPoint *********//
    const res2 = await request.post("/api/v2/users/forget-password", {
        timeout: 3000,
        data: forgetPassPayload
    })

    let resBody2 = await res2.json();
    console.log(resBody2);

    expect(res2.status()).toBe(200); 
    expect(res2.statusText()).toBe("OK"); 


});

/*
generate test plan and cases for this end points "/api/v2/businesses/add-bank-info" 
that try to "break" or exploit the API. Think like an ethical hacker: What could go wrong? 
Can a user access something they shouldn't?
Try to find weaknesses in them — things like broken
authentication, injection flaws, data exposure, etc.
This end point require a token generated by "/api/v2/users/generate-token-for-interview-task" 
so i take token and insert it in api header 
log response and see if there is any vulnerability

-----------------Copilot response 
api-security-exploits.spec.ts — new. Single test covering multiple exploit-style cases against:
POST /api/v2/pickups (control, missing auth, injection, oversized/negative values, malformed contact, tampered businessLocationId, rapid repeated calls). Each pickup POST uses a unique scheduledDate starting in 2026.
POST /api/v2/users/forget-password (control, missing body, enumeration probes).
Each request checks that no 5xx server error occurs and performs simple assertions for expected behavior.


{
  success: false,
  message: 'User is not authorized!. Not authorized to update param: [bankInfo.مصر]',
  errorCode: 1007
}

 */

